-- Update booking_confirmation email template to include QR code image
-- This template is rendered with placeholders replaced by the NotificationService

UPDATE "EmailTemplates"
SET 
    "Subject" = 'Booking Confirmed - {{booking_reference}}',
    "BodyHtml" = 
'<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmation</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 28px;">🎉 Booking Confirmed!</h1>
    </div>
    
    <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
        
        <p style="font-size: 16px;">Hi <strong>{{customer_name}}</strong>,</p>
        
        <p>Your booking has been confirmed! We''re excited to serve you.</p>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #667eea;">
            <h3 style="margin-top: 0; color: #667eea;">📋 Booking Details</h3>
            <p style="margin: 8px 0;"><strong>Booking Reference:</strong> <span style="color: #667eea; font-size: 18px;">{{booking_reference}}</span></p>
            <p style="margin: 8px 0;"><strong>Vehicle:</strong> {{vehicle_make}} {{vehicle_model}} ({{vehicle_plate}})</p>
            <p style="margin: 8px 0;"><strong>Type:</strong> {{vehicle_type}}</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;">
            
            <p style="margin: 8px 0;"><strong>📅 Pickup:</strong> {{pickup_date}} at {{pickup_time}}</p>
            <p style="margin: 8px 0;"><strong>📍 Pickup Location:</strong> {{pickup_location}}</p>
            
            <p style="margin: 8px 0;"><strong>📅 Return:</strong> {{return_date}} at {{return_time}}</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;">
            
            <p style="font-size: 20px; margin: 15px 0 0 0;"><strong>💰 Total Amount:</strong> <span style="color: #667eea;">{{currency}} {{total_amount}}</span></p>
        </div>
        
        <!-- QR Code Section -->
        <div style="background: white; padding: 30px; border-radius: 8px; text-align: center; margin: 20px 0; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #667eea; margin-top: 0; margin-bottom: 10px;">✳️ Your Booking QR Code</h3>
            <p style="color: #666; margin-bottom: 20px; font-size: 14px;">Show this QR code during pickup for express check-in</p>
            
            <!-- QR Code Image - generated by backend -->
            <img src="{{qr_code_image}}" alt="Booking QR Code" style="max-width: 250px; height: auto; border: 3px solid #667eea; border-radius: 12px; padding: 15px; background: white; display: inline-block;" />
            
            <p style="font-size: 13px; color: #999; margin-top: 15px; font-weight: bold;">{{booking_reference}}</p>
            <p style="font-size: 11px; color: #aaa; margin-top: 5px;">Scan this code at pickup location</p>
        </div>
        
        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; border-left: 4px solid #ffc107; margin: 20px 0;">
            <p style="margin: 0 0 10px 0; color: #856404;"><strong>📱 Next Steps:</strong></p>
            <ul style="margin: 10px 0; padding-left: 20px; color: #856404;">
                <li style="margin: 5px 0;">Save this email or take a screenshot of the QR code</li>
                <li style="margin: 5px 0;">Arrive at pickup location on time</li>
                <li style="margin: 5px 0;">Show QR code to complete vehicle inspection</li>
                <li style="margin: 5px 0;">Enjoy your ride! 🚗</li>
            </ul>
        </div>
        
        <div style="background: #e7f3ff; padding: 20px; border-radius: 8px; border-left: 4px solid #2196F3; margin: 20px 0;">
            <p style="margin: 0 0 10px 0; color: #1976D2;"><strong>💡 Important Reminders:</strong></p>
            <ul style="margin: 10px 0; padding-left: 20px; color: #1565C0; font-size: 14px;">
                <li style="margin: 5px 0;">Bring a valid driver''s license</li>
                <li style="margin: 5px 0;">Vehicle inspection is required before departure</li>
                <li style="margin: 5px 0;">Late returns may incur additional charges</li>
            </ul>
        </div>
        
        <div style="text-align: center; margin: 30px 0; padding: 20px; background: white; border-radius: 8px;">
            <p style="color: #666; margin-bottom: 10px;">Need help? Contact us:</p>
            <p style="margin: 5px 0;"><strong>📞 Phone:</strong> <a href="tel:{{support_phone}}" style="color: #667eea; text-decoration: none;">{{support_phone}}</a></p>
            <p style="margin: 5px 0;"><strong>📧 Email:</strong> <a href="mailto:{{support_email}}" style="color: #667eea; text-decoration: none;">{{support_email}}</a></p>
        </div>
        
        <div style="background: #f0f0f0; padding: 20px; border-radius: 8px; text-align: center; margin-top: 30px;">
            <p style="margin: 0; font-size: 14px; color: #666; font-weight: bold;">Thank you for choosing Ryve Rental! 🚙</p>
            <p style="margin: 10px 0 0 0; font-size: 12px; color: #999;">Drive safe, drive smart.</p>
        </div>
        
    </div>
    
    <div style="text-align: center; padding: 20px; font-size: 11px; color: #999;">
        <p style="margin: 5px 0;">This is an automated message. Please do not reply to this email.</p>
        <p style="margin: 5px 0;">© 2025 Ryve Rental. All rights reserved.</p>
    </div>
    
</body>
</html>'
WHERE "Name" = 'booking_confirmation';

-- If the template doesn't exist yet, insert it
INSERT INTO "EmailTemplates" ("Name", "Subject", "BodyHtml", "Category", "Description", "IsActive", "CreatedAt")
SELECT 
    'booking_confirmation',
    'Booking Confirmed - {{booking_reference}}',
    '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmation</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 28px;">🎉 Booking Confirmed!</h1>
    </div>
    
    <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
        
        <p style="font-size: 16px;">Hi <strong>{{customer_name}}</strong>,</p>
        
        <p>Your booking has been confirmed! We''re excited to serve you.</p>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #667eea;">
            <h3 style="margin-top: 0; color: #667eea;">📋 Booking Details</h3>
            <p style="margin: 8px 0;"><strong>Booking Reference:</strong> <span style="color: #667eea; font-size: 18px;">{{booking_reference}}</span></p>
            <p style="margin: 8px 0;"><strong>Vehicle:</strong> {{vehicle_make}} {{vehicle_model}} ({{vehicle_plate}})</p>
            <p style="margin: 8px 0;"><strong>Type:</strong> {{vehicle_type}}</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;">
            
            <p style="margin: 8px 0;"><strong>📅 Pickup:</strong> {{pickup_date}} at {{pickup_time}}</p>
            <p style="margin: 8px 0;"><strong>📍 Pickup Location:</strong> {{pickup_location}}</p>
            
            <p style="margin: 8px 0;"><strong>📅 Return:</strong> {{return_date}} at {{return_time}}</p>
            
            <hr style="border: none; border-top: 1px solid #eee; margin: 15px 0;">
            
            <p style="font-size: 20px; margin: 15px 0 0 0;"><strong>💰 Total Amount:</strong> <span style="color: #667eea;">{{currency}} {{total_amount}}</span></p>
        </div>
        
        <!-- QR Code Section -->
        <div style="background: white; padding: 30px; border-radius: 8px; text-align: center; margin: 20px 0; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #667eea; margin-top: 0; margin-bottom: 10px;">✳️ Your Booking QR Code</h3>
            <p style="color: #666; margin-bottom: 20px; font-size: 14px;">Show this QR code during pickup for express check-in</p>
            
            <!-- QR Code Image - generated by backend -->
            <img src="{{qr_code_image}}" alt="Booking QR Code" style="max-width: 250px; height: auto; border: 3px solid #667eea; border-radius: 12px; padding: 15px; background: white; display: inline-block;" />
            
            <p style="font-size: 13px; color: #999; margin-top: 15px; font-weight: bold;">{{booking_reference}}</p>
            <p style="font-size: 11px; color: #aaa; margin-top: 5px;">Scan this code at pickup location</p>
        </div>
        
        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; border-left: 4px solid #ffc107; margin: 20px 0;">
            <p style="margin: 0 0 10px 0; color: #856404;"><strong>📱 Next Steps:</strong></p>
            <ul style="margin: 10px 0; padding-left: 20px; color: #856404;">
                <li style="margin: 5px 0;">Save this email or take a screenshot of the QR code</li>
                <li style="margin: 5px 0;">Arrive at pickup location on time</li>
                <li style="margin: 5px 0;">Show QR code to complete vehicle inspection</li>
                <li style="margin: 5px 0;">Enjoy your ride! 🚗</li>
            </ul>
        </div>
        
        <div style="background: #e7f3ff; padding: 20px; border-radius: 8px; border-left: 4px solid #2196F3; margin: 20px 0;">
            <p style="margin: 0 0 10px 0; color: #1976D2;"><strong>💡 Important Reminders:</strong></p>
            <ul style="margin: 10px 0; padding-left: 20px; color: #1565C0; font-size: 14px;">
                <li style="margin: 5px 0;">Bring a valid driver''s license</li>
                <li style="margin: 5px 0;">Vehicle inspection is required before departure</li>
                <li style="margin: 5px 0;">Late returns may incur additional charges</li>
            </ul>
        </div>
        
        <div style="text-align: center; margin: 30px 0; padding: 20px; background: white; border-radius: 8px;">
            <p style="color: #666; margin-bottom: 10px;">Need help? Contact us:</p>
            <p style="margin: 5px 0;"><strong>📞 Phone:</strong> <a href="tel:{{support_phone}}" style="color: #667eea; text-decoration: none;">{{support_phone}}</a></p>
            <p style="margin: 5px 0;"><strong>📧 Email:</strong> <a href="mailto:{{support_email}}" style="color: #667eea; text-decoration: none;">{{support_email}}</a></p>
        </div>
        
        <div style="background: #f0f0f0; padding: 20px; border-radius: 8px; text-align: center; margin-top: 30px;">
            <p style="margin: 0; font-size: 14px; color: #666; font-weight: bold;">Thank you for choosing Ryve Rental! 🚙</p>
            <p style="margin: 10px 0 0 0; font-size: 12px; color: #999;">Drive safe, drive smart.</p>
        </div>
        
    </div>
    
    <div style="text-align: center; padding: 20px; font-size: 11px; color: #999;">
        <p style="margin: 5px 0;">This is an automated message. Please do not reply to this email.</p>
        <p style="margin: 5px 0;">© 2025 Ryve Rental. All rights reserved.</p>
    </div>
    
</body>
</html>',
    'customer',
    'Booking confirmation email sent to customers with QR code',
    true,
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM "EmailTemplates" WHERE "Name" = 'booking_confirmation'
);
